# Generated by Django 2.2.3 on 2020-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20200922_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(default=None, upload_to='pokemons'),
            preserve_default=False,
        ),
    ]
