# Generated by Django 2.2.3 on 2020-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20200922_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='health',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(default='some desc', max_length=2000),
            preserve_default=False,
        ),
    ]
